allowBuilds:
  '@tsparticles/engine': true
  '@whiskeysockets/baileys': true
  esbuild: true
  msw: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
overrides:
  browserslist: '>=4.28.7'
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
