export const en = {
  common: {
    save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", create: "Create", search: "Search", filter: "Filter", clear: "Clear", apply: "Apply", close: "Close", loading: "Loading", back: "Back", continue: "Continue", confirm: "Confirm", retry: "Try again", done: "Done", today: "Today", tomorrow: "Tomorrow", all: "All", active: "Active", inactive: "Inactive", pending: "Pending", confirmed: "Confirmed", cancelled: "Cancelled", completed: "Completed", more: "More", yes: "Yes", no: "No", next: "Next", previous: "Previous", refresh: "Refresh", upgrade: "Upgrade", comparePlans: "Compare plans",
  },
  dashboard: {
    confirm: "Confirm", cancel: "Cancel", cash: "Cash", mbway: "MB Way", card: "Card", overview: "Overview", appointments: "Appointments", clients: "Clients", services: "Services", professionals: "Professionals", revenue: "Revenue", queue: "Queue", settings: "Settings", menu: "Menu", closeMenu: "Close menu", openMenu: "Open menu", allSections: "All dashboard sections", quickNavigation: "Dashboard quick navigation", mainNavigation: "Dashboard main navigation", backToOverview: "Back to overview", backToSite: "Back to website", currentTime: "Current time {time}", checkingTime: "Loading current time", upgradeFeature: "{feature} is available on a higher plan.", upgradeDescription: "You can keep using Silentra without upgrading. If you need this feature, compare plans.", qrCode: "QR code", team: "Team", messages: "Messages", analytics: "Analytics", marketing: "Marketing", automations: "Automations", loyalty: "Loyalty", pos: "Point of sale", billing: "Plan and billing",
  },
  loyalty: { title: "Points and rewards", kicker: "LOYALTY", subtitle: "Configure how clients earn points, what they can redeem, and validate rewards at the counter.", programRules: "Program rules", programState: "Program status", programActive: "Program active", disabledDescription: "When disabled, the public card disappears and new enrollments, access and redemptions are blocked.", pointsPerEuro: "Points per €1 spent", welcomePoints: "Welcome points", referralPoints: "Referral points", saveRules: "Save rules", savingRules: "Saving…", programEnabled: "Loyalty program enabled.", programDisabled: "Loyalty program disabled.", summary: "Summary", state: "Status", conversion: "Base conversion", activeRewards: "Active rewards", rewards: "Rewards", rewardsDescription: "Keep rewards simple, clear and easy to redeem.", newReward: "New reward", editReward: "Edit reward", rewardName: "Name", rewardNamePlaceholder: "e.g. Free haircut", rewardPoints: "Points required", rewardDescription: "Description", rewardDescriptionPlaceholder: "Clients see this explanation when redeeming.", rewardType: "Type", discount: "Discount", freeService: "Free service", custom: "Custom", rewardValue: "Value (optional)", rewardValuePlaceholder: "e.g. 5", saving: "Save", savingReward: "Saving…", rewardCreated: "Reward created.", rewardUpdated: "Reward updated.", rewardDisabled: "Reward disabled.", deactivateRewardConfirm: "Disable this reward? Previous redemptions remain in history.", points: "Points", validate: "Validate", refreshLoyalty: "Refresh loyalty", loaded: "Loyalty loaded.", loadingLoyalty: "Loading loyalty…", accessChecking: "Checking loyalty access…", upgradeTitle: "Loyalty program", upgradeDescription: "Create points and rewards to encourage clients to come back.", skipContent: "Skip to content" },
  admin: { loyaltyPoints: "Points management", searchCustomer: "Find customer", customerEmail: "Customer email", searchCustomerPlaceholder: "customer@email.com", findCustomer: "Search", assignPoints: "Grant points", pointsAmount: "Points amount", reason: "Reason", reasonPlaceholder: "e.g. Service delay compensation", memberFound: "Customer found", balance: "Balance", barbershop: "Barbershop" },
  booking: { confirm: "Confirm booking", confirmed: "Booking confirmed", cancel: "Cancel booking", reschedule: "Reschedule", service: "Service", professional: "Professional", date: "Date", time: "Time", address: "Address", addGoogleCalendar: "Add to Google Calendar", addAppleCalendar: "Add to Apple Calendar", viewGoogleMaps: "View on Google Maps", viewAppleMaps: "View on Apple Maps" },
  email: { bookingSubject: "Booking confirmed — {barbershop}", loyaltySubject: "Redemption confirmed — {barbershop}", redemptionCreated: "Your redemption at {barbershop} was created.", redemptionCode: "Redemption code", showQr: "Show this QR code at the counter.", codeFallback: "If you cannot use the QR code, show this code instead." },
  nav: { barbershops: "Barbershops", howItWorks: "How it works", forBarbers: "For barbers", dashboard: "Dashboard", settings: "Settings", plans: "Plans", stats: "Stats", signIn: "Sign in", logout: "Log out", manageBookings: "Manage bookings" },
  legal: { termsTitle: "Terms & Conditions", termsLastUpdated: "Silentra for Barbers — last updated: {date}", agreePrefix: "I agree to the", termsLink: "Terms & Conditions", acceptRequired: "You must accept the Terms & Conditions." },
  landing: { navContrast: "Friction contrast", navDashboard: "Dashboard", navAccess: "Access", enterDashboard: "Enter dashboard", heroKicker: "Premium booking infrastructure for modern barbershops", heroTitleLine1: "Silentra", heroTitleLine2: "for barbers", heroSubtitle: "Zero Friction means clients book in seconds through the browser. No app downloads. No account creation. Just a clean path from intent to confirmed appointment.", simulatorLabel: "Interactive micro-booking simulator", simulatorTitle: "Pick a service, choose a slot, confirm instantly.", simulatorInstant: "Instant flow", simulatorSuccess: "Confirmed", chooseTime: "Choose time", simulatorSummary: "Selected:", confirmBooking: "Confirm booking", successTitle: "Booking confirmed", successMeta: "Zero friction, no app, no account", simulatorHint: "Try selecting a service and time slot. The success state mirrors the client experience Silentra is designed to deliver.", liveSignal: "Live signal", liveSignalCopy: "This is the customer-facing motion the owner sees: fast decisions, clean confirmation, and no onboarding wall.", noApp: "No app", smsWhatsApp: "SMS", oldWayTitle: "The old way", silentraWayTitle: "The Silentra way", dashboardKicker: "The command center", dashboardTitle: "A high-fidelity dashboard built for operational clarity.", dashboardSubtitle: "Appointments, revenue, queue signals, and automated outreach in one premium interface.", calendarCore: "Calendar core", revenueKicker: "Analytics snapshot", recentBookingsKicker: "Frictionless queue", outreachKicker: "Automated outreach", ctaKicker: "High-intent access", ctaTitle: "Request access and launch a cleaner booking experience.", ctaSubtitle: "Use a single email or phone field to start the conversation. Silentra keeps the path to conversion short and elegant.", ctaPlaceholder: "Email or phone", ctaButton: "Request access" },
  auth: { loginTitle: "Sign in", loginSubtitle: "Access your dashboard and manage your shop in real time.", registerTitle: "Create account", registerSubtitle: "Start setting up your digital presence.", email: "Email", password: "Password", forgotPassword: "Forgot your password?", rememberMe: "Keep me signed in", signIn: "Sign in", signUp: "Create account", noAccount: "Don't have an account yet?", haveAccount: "Already have an account?", continueWith: "Continue with", backToApp: "Back to app" },
  onboarding: { title: "Set up your barbershop", subtitle: "Complete a few steps. Your progress is saved so you can continue later.", createTitle: "Create barbershop", createSubtitle: "Start with the essential details. You can complete the rest later.", joinTitle: "Join a barbershop", joinSubtitle: "Use the invite you received from your team.", barbershopName: "Barbershop name", ownerName: "Owner name", inviteCode: "Invite code", createBtn: "Create barbershop", joinBtn: "Join barbershop", successTitle: "Your barbershop is ready", successDescription: "The essentials are ready. Now add services, professionals and opening hours." },
  marketplace: { title: "Find a barbershop", subtitle: "Search, compare and book in seconds.", searchPlaceholder: "Search shops, services, or locations", filterOpenNow: "Open now", filterPopular: "Most popular", filterNearby: "Near me", filterTopRated: "Top rated", featured: "Featured", noResults: "No results found.", bookNow: "Book now", instantBooking: "Instant booking", noAppRequired: "No app required", mapTitle: "Availability", mapSubtitle: "Find locations with available times." },
  stats: { title: "Stats", subtitle: "Understand your barbershop performance without the complexity.", monthlyRevenue: "Monthly revenue", appointmentsCompleted: "Appointments completed", newClients: "New clients", cancellationRate: "Cancellation rate", growth: "Growth" },
  settings: { title: "Settings", subtitle: "Configure Silentra around the way you work.", businessHours: "Business hours", closedDays: "Closed days", workingDays: "Working days", language: "Language", notifications: "Notifications", bookingRules: "Booking rules" },
  notFound: { status: "HTTP 404 · Page not found", statusCode: "Status code", title: "This page doesn't exist", description: "The route you requested was not found. It may have been moved, deleted, or the URL may be incorrect.", backHome: "Back to home", footer: "barbers.silentra.me · not found" },
} as const;
