export const pt = {
  common: {
    save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", create: "Criar", search: "Pesquisar", filter: "Filtrar", clear: "Limpar", apply: "Aplicar", close: "Fechar", loading: "A carregar", back: "Voltar", continue: "Continuar", confirm: "Confirmar", retry: "Tentar novamente", done: "Concluído", today: "Hoje", tomorrow: "Amanhã", all: "Tudo", active: "Ativo", inactive: "Inativo", pending: "Pendente", confirmed: "Confirmado", cancelled: "Cancelado", completed: "Concluído", more: "Mais", yes: "Sim", no: "Não", next: "Seguinte", previous: "Anterior", refresh: "Atualizar", upgrade: "Fazer upgrade", comparePlans: "Comparar planos",
  },
  dashboard: {
    confirm: "Confirmar", cancel: "Cancelar", cash: "Dinheiro", mbway: "MB WAY", card: "Cartão", overview: "Visão geral", appointments: "Agendamentos", clients: "Clientes", services: "Serviços", professionals: "Profissionais", revenue: "Receita", queue: "Fila de espera", settings: "Definições", menu: "Menu", closeMenu: "Fechar menu", openMenu: "Abrir menu", allSections: "Todas as secções do painel", quickNavigation: "Navegação rápida do painel", mainNavigation: "Navegação principal do painel", backToOverview: "Voltar à visão geral", backToSite: "Voltar ao site", currentTime: "Hora atual {time}", checkingTime: "A carregar a hora atual", upgradeFeature: "{feature} está disponível num plano superior.", upgradeDescription: "Podes continuar a usar a Silentra sem fazer upgrade. Se precisares desta funcionalidade, compara os planos.", qrCode: "Código QR", team: "Equipa", messages: "Mensagens", analytics: "Análise", marketing: "Marketing", automations: "Automações", loyalty: "Fidelização", pos: "Ponto de venda", billing: "Plano e faturação",
  },
  loyalty: { title: "Pontos e recompensas", kicker: "FIDELIZAÇÃO", subtitle: "Configura como os clientes acumulam pontos, o que podem resgatar e valida as recompensas no balcão.", programRules: "Regras do programa", programState: "Estado do programa", programActive: "Programa ativo", disabledDescription: "Quando desligado, o card público desaparece e novas adesões, acessos e resgates ficam bloqueados.", pointsPerEuro: "€1 gasto = pontos", welcomePoints: "Pontos de boas-vindas", referralPoints: "Pontos de referência", saveRules: "Guardar regras", savingRules: "A guardar…", programEnabled: "Programa de fidelização ativado.", programDisabled: "Programa de fidelização desativado.", summary: "Resumo", state: "Estado", conversion: "Conversão base", activeRewards: "Recompensas ativas", rewards: "Recompensas", rewardsDescription: "Mantém as recompensas simples, claras e fáceis de resgatar.", newReward: "Nova recompensa", editReward: "Editar recompensa", rewardName: "Nome", rewardNamePlaceholder: "Ex.: Corte gratuito", rewardPoints: "Pontos necessários", rewardDescription: "Descrição", rewardDescriptionPlaceholder: "O cliente vê esta explicação ao resgatar.", rewardType: "Tipo", discount: "Desconto", freeService: "Serviço gratuito", custom: "Personalizada", rewardValue: "Valor (opcional)", rewardValuePlaceholder: "Ex.: 5", saving: "Guardar", savingReward: "A guardar…", rewardCreated: "Recompensa criada.", rewardUpdated: "Recompensa atualizada.", rewardDisabled: "Recompensa desativada.", deactivateRewardConfirm: "Desativar esta recompensa? Os resgates anteriores continuam no histórico.", points: "Pontos", validate: "Validar", refreshLoyalty: "Atualizar fidelização", loaded: "Fidelização carregada.", loadingLoyalty: "A carregar a fidelização…", accessChecking: "A verificar o acesso à fidelização…", upgradeTitle: "Programa de fidelização", upgradeDescription: "Cria pontos e recompensas para incentivar os clientes a voltar.", skipContent: "Saltar para o conteúdo" },
  admin: { loyaltyPoints: "Gestão de pontos", searchCustomer: "Pesquisar cliente", customerEmail: "Email do cliente", searchCustomerPlaceholder: "cliente@email.com", findCustomer: "Pesquisar", assignPoints: "Atribuir pontos", pointsAmount: "Quantidade de pontos", reason: "Motivo", reasonPlaceholder: "Ex.: Compensação por atraso", memberFound: "Cliente encontrado", balance: "Saldo", barbershop: "Barbearia" },
  booking: { confirm: "Confirmar agendamento", confirmed: "Agendamento confirmado", cancel: "Cancelar agendamento", reschedule: "Reagendar", service: "Serviço", professional: "Profissional", date: "Data", time: "Hora", address: "Morada", addGoogleCalendar: "Adicionar ao Google Calendar", addAppleCalendar: "Adicionar ao Apple Calendar", viewGoogleMaps: "Ver no Google Maps", viewAppleMaps: "Ver no Apple Maps" },
  email: { bookingSubject: "Agendamento confirmado — {barbershop}", loyaltySubject: "Resgate confirmado — {barbershop}", redemptionCreated: "O teu resgate na {barbershop} foi criado.", redemptionCode: "Código de resgate", showQr: "Apresenta este QR code no balcão.", codeFallback: "Se não conseguires usar o QR code, apresenta este código." },
  nav: { barbershops: "Barbearias", howItWorks: "Como funciona", forBarbers: "Para barbeiros", dashboard: "Painel", plans: "Planos", settings: "Definições", stats: "Estatísticas", signIn: "Entrar", logout: "Sair", manageBookings: "Gerir agendamentos" },
  legal: { termsTitle: "Termos e Condições", termsLastUpdated: "Silentra para Barbeiros — última atualização: {date}", agreePrefix: "Aceito os", termsLink: "Termos e Condições", acceptRequired: "Tens de aceitar os Termos e Condições." },
  landing: { navContrast: "Menos fricção", navDashboard: "Painel", navAccess: "Acesso", enterDashboard: "Entrar no painel", heroKicker: "Gestão e reservas para barbearias modernas", heroTitleLine1: "Silentra", heroTitleLine2: "para barbeiros", heroSubtitle: "Os teus clientes marcam em segundos através do navegador. Sem aplicações, sem contas e sem formulários desnecessários.", simulatorLabel: "Experimenta antes de criar conta", simulatorTitle: "Escolhe um serviço, vê uma hora disponível e confirma.", simulatorInstant: "Fluxo rápido", simulatorSuccess: "Confirmado", chooseTime: "Escolher hora", simulatorSummary: "Selecionado:", confirmBooking: "Confirmar reserva", successTitle: "Reserva confirmada", successMeta: "Sem aplicação e sem conta", simulatorHint: "Experimenta o fluxo. Primeiro vê o valor; só depois te pedimos os dados necessários.", liveSignal: "Experiência em tempo real", liveSignalCopy: "Menos decisões, menos campos e um caminho claro até à reserva.", noApp: "Sem aplicação", smsWhatsApp: "SMS", oldWayTitle: "O método antigo", silentraWayTitle: "O método Silentra", dashboardKicker: "O centro de comando", dashboardTitle: "Tudo o que precisas para gerir a tua barbearia, num só lugar.", dashboardSubtitle: "Agendamentos, receita, fila de espera e comunicação numa interface simples.", calendarCore: "Agenda", revenueKicker: "Resumo financeiro", recentBookingsKicker: "Próximos agendamentos", outreachKicker: "Comunicação automática", ctaKicker: "Começa sem compromisso", ctaTitle: "Experimenta a Silentra e começa a aceitar reservas.", ctaSubtitle: "Cria a tua barbearia em poucos passos. O plano gratuito permite começar sem cartão.", ctaPlaceholder: "O teu email", ctaButton: "Começar grátis" },
  auth: { loginTitle: "Entrar", loginSubtitle: "Acede ao painel e gere a tua barbearia.", registerTitle: "Criar conta", registerSubtitle: "Começa a configurar a tua barbearia.", email: "Email", password: "Palavra-passe", forgotPassword: "Esqueceste-te da palavra-passe?", rememberMe: "Manter sessão iniciada", signIn: "Entrar", signUp: "Criar conta", noAccount: "Ainda não tens conta?", haveAccount: "Já tens conta?", continueWith: "Continuar com", backToApp: "Voltar à aplicação" },
  onboarding: { title: "Vamos configurar a tua barbearia", subtitle: "Só precisas de completar alguns passos. Guardamos o progresso para não perderes o que já fizeste.", createTitle: "Criar barbearia", createSubtitle: "Começa com os dados essenciais. Podes completar o resto depois.", joinTitle: "Entrar numa barbearia", joinSubtitle: "Usa o convite que recebeste da tua equipa.", barbershopName: "Nome da barbearia", ownerName: "Nome do responsável", inviteCode: "Código de convite", createBtn: "Criar barbearia", joinBtn: "Entrar na barbearia", successTitle: "A tua barbearia está criada", successDescription: "O essencial está pronto. Agora podes adicionar serviços, profissionais e horários." },
  marketplace: { title: "Encontrar uma barbearia", subtitle: "Pesquisa, compara e marca em segundos.", searchPlaceholder: "Pesquisar barbearia, serviço ou localização", filterOpenNow: "Aberto agora", filterPopular: "Mais populares", filterNearby: "Perto de mim", filterTopRated: "Melhor avaliadas", featured: "Destacadas", noResults: "Não encontrámos resultados.", bookNow: "Marcar agora", instantBooking: "Reserva imediata", noAppRequired: "Sem aplicação", mapTitle: "Disponibilidade", mapSubtitle: "Encontra espaços com horários disponíveis." },
  stats: { title: "Estatísticas", subtitle: "Percebe o desempenho da tua barbearia sem complicações.", monthlyRevenue: "Receita mensal", appointmentsCompleted: "Atendimentos concluídos", newClients: "Novos clientes", cancellationRate: "Taxa de cancelamento", growth: "Crescimento" },
  settings: { title: "Definições", subtitle: "Configura a Silentra de acordo com a forma como trabalhas.", businessHours: "Horário de funcionamento", closedDays: "Dias de encerramento", workingDays: "Dias de trabalho", language: "Idioma", notifications: "Notificações", bookingRules: "Regras de reserva" },
  notFound: { status: "HTTP 404 · Página não encontrada", statusCode: "Código de estado", title: "Esta página não existe", description: "A rota que procuraste não foi encontrada. Pode ter sido movida, eliminada ou o URL pode estar incorreto.", backHome: "Voltar ao início", footer: "barbers.silentra.me · não encontrada" },
} as const;
